spring.application.name=Zorvyn

server.port=8080

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:23283/railway
spring.datasource.username=root
spring.datasource.password=EuQhnTIMbCGFoysxCLXEKDOnCESYFqhS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.token.secret=zorvyn-super-secret-change-this
security.token.ttl-minutes=120

